/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pratik
 */
import javax.swing.*;
public class unitConverter extends javax.swing.JFrame {
    // New Frame for Error Message
    JFrame errorFrame;
    /**
     * Creates new form unitConverter
     */
    public unitConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        enterAmountLabel = new javax.swing.JLabel();
        amountTextField = new javax.swing.JTextField();
        rateLabel = new javax.swing.JLabel();
        convertedPriceTextField = new javax.swing.JTextField();
        convertedPriceLabel = new javax.swing.JLabel();
        pTOdRadioButton = new javax.swing.JRadioButton();
        dTOpRadioButton = new javax.swing.JRadioButton();
        convertLabel = new javax.swing.JLabel();
        rateComboBox = new javax.swing.JComboBox<>();
        goButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unit Converter");

        enterAmountLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        enterAmountLabel.setText("Enter your amount:");

        amountTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        rateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rateLabel.setText("Rate:");

        convertedPriceTextField.setEditable(false);
        convertedPriceTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        convertedPriceLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        convertedPriceLabel.setText("Converted Price");

        buttonGroup1.add(pTOdRadioButton);
        pTOdRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pTOdRadioButton.setText("Pound to Dollar");
        pTOdRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pTOdRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(dTOpRadioButton);
        dTOpRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dTOpRadioButton.setText("Dollar to Pound");
        dTOpRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dTOpRadioButtonActionPerformed(evt);
            }
        });

        convertLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        convertLabel.setText("Convert");

        rateComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Select Rate ---", "1.29", "0.77" }));
        rateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateComboBoxActionPerformed(evt);
            }
        });

        goButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        goButton.setText("Go");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(convertedPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enterAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(convertLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pTOdRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(dTOpRadioButton))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addComponent(convertedPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(259, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(convertedPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pTOdRadioButton)
                    .addComponent(dTOpRadioButton)
                    .addComponent(convertLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(98, 98, 98)
                    .addComponent(convertedPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(227, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>                        

    private void pTOdRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        rateComboBox.setSelectedIndex(1);
    }                                               

    private void dTOpRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        rateComboBox.setSelectedIndex(2);
    }                                               

    private void rateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        String selectedComboBox = (String) rateComboBox.getSelectedItem();
        if ("1.29".equals(selectedComboBox)){
            pTOdRadioButton.setSelected(true);
            dTOpRadioButton.setSelected(false);
        }else if ("0.77".equals(selectedComboBox)){
            dTOpRadioButton.setSelected(true);
            pTOdRadioButton.setSelected(false);
        }else  if ("--- Select Rate ---".equals(selectedComboBox)){
            buttonGroup1.clearSelection();
        }
    }                                            

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        buttonGroup1.clearSelection();
        amountTextField.setText("");
        convertedPriceTextField.setText("");
        rateComboBox.setSelectedIndex(0);
    }                                           

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String selectedComboBox = (String) rateComboBox.getSelectedItem();
        try{
            if ("--- Select Rate ---".equals(selectedComboBox) && amountTextField.getText().equals("")){
                errorFrame = new JFrame();
                JOptionPane.showMessageDialog(errorFrame,"Inputs not found","Error",JOptionPane.WARNING_MESSAGE);  
            }    
            else if ("--- Select Rate ---".equals(selectedComboBox)){
                 errorFrame = new JFrame();
                JOptionPane.showMessageDialog(errorFrame,"Please select the rate","Error",JOptionPane.WARNING_MESSAGE);
            }else if(amountTextField.getText().equals("")){
                errorFrame = new JFrame();
                JOptionPane.showMessageDialog(errorFrame,"Please enter an amount");
            }else{
                double enteredAmount= Double.parseDouble(amountTextField.getText());
                if (pTOdRadioButton.isSelected()==true){
                    String converted = Double.toString(1.29*enteredAmount);
                    convertedPriceTextField.setText(converted);
                }else if(pTOdRadioButton.isSelected()==false){
                    String converted = Double.toString(0.77*enteredAmount);
                    convertedPriceTextField.setText(converted);
                }
                
            }
            
        }
        catch (Exception e){
            errorFrame = new JFrame();
            JOptionPane.showMessageDialog(errorFrame,"Please enter numbers only");
        }
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(unitConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(unitConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(unitConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(unitConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new unitConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField amountTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel convertLabel;
    private javax.swing.JLabel convertedPriceLabel;
    private javax.swing.JTextField convertedPriceTextField;
    private javax.swing.JRadioButton dTOpRadioButton;
    private javax.swing.JLabel enterAmountLabel;
    private javax.swing.JButton goButton;
    private javax.swing.JRadioButton pTOdRadioButton;
    private javax.swing.JComboBox<String> rateComboBox;
    private javax.swing.JLabel rateLabel;
    // End of variables declaration                   
}
